Add support for Godot 4.0
godot-extended-libraries/godot-plugin-refresher pull request #19
Opened 2021-08-21 13:45 UTC by nonunknown

PS: The confirmation dialog needs rework! I couldnt find a solution! But the rest works fine!

2021-08-21 21:34 UTC, willnationsdev requested changes
@nonunknown Thanks for your interest in migrating this to 4.0! Looking okay so far - just a few things to adjust and double-check. Let me know if you have any questions.

2021-08-21 21:34 UTC, willnationsdev commented on .gitignore
> +
Why these two extra lines? Can remove.

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +
The trailing tab on this line is causing the static analysis check on GitHub to fail. Since you need 2 newlines in between each function, just remove this line 13 and it should work fine.

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher.tscn
>  dialog_autowrap = true
Seems like many property values in the scene completely changed (and not just renamed, but now actually missing a lot of info that was there before. Did you do this manually yourself, or did you just save the scene and the Godot Editor updated the scene data this way automatically? Does the GUI *look* any different, or does it look the same?

Seems like *most* of it is just margin adjustments which can likely be explained by the Godot Editor itself being organized differently than it was before, in which case, most of the changes are probably fine.

However, it looks like we lost the `window_title` on the ConfirmationDialog as well as its `rect_min_size`. I'm guessing the property names changed, so you'll need to re-add that "Plugin Refresher" title and update the minimum rect size to match (however that's done now).

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher.tscn
> -[connection signal="pressed" from="RefreshButton" to="." method="_on_RefreshButton_pressed"]
We also lost this signal connection, again, likely because of an API change. Re-add the signal connection to the scene info please.

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +var ps:PackedScene = preload("res://addons/godot-plugin-refresher/plugin_refresher.tscn")
1. If you're going to do type hints, please favor static type inference over explicitness:

    ```gdscript
    const ADDONS_PATH := StringName(...)
    ```
 
2. If you're going to use a `StringName` literal in GDScript, please use the shorthand syntax:

    ```gdscript
    const ADDONS_PATH := &"res://addons/"
    ```

3. The `ps` variable has a preloaded value, so it should be declared as a `const` with a `CONST_CASE` name.
4. `ps` is not a very descriptive name. Something like `WIDGET_SCN` might be better.
5. I can't quite remember if I have other path-based dependencies elsewhere in here, but there's a reason I used a relative file path previously in the `preload` operation above. If someone were to rename the plugin directory name, then suddenly the plugin would stop working (have had to fix that issue before). We want to avoid that if possible by demanding only the path relative to *this* script, within the same plugin folder.

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +	refresher.connect("confirm_refresh_plugin", _on_confirm_refresh_plugin)
You got the local methods swapped out with callables, but you're still using the stringly-typed `connect` method. Switch to directly accessing the `Signal` instance and calling *its* `connect` method.

```gdscript
efs.filesystem_changed.connect(_on_filesystem_changed)
refresher.request_refresh_plugin.connect(_on_request_refresh_plugin)
refresher.confirm_refresh_plugin.connect(_on_confirm_refresh_plugin)
```

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +const PLUGIN_CONFIG:StringName = StringName( "settings.cfg" )
While `SETTINGS` and `SETTING_RECENT` are both actual property names and should be `StringName`, the above 3 properties are all file paths and should inherently be `String` instances since they are only ever used in combination with other strings to dynamically compose string values. They aren't involved in "lookup" operations in any index-based data structures.

2021-08-21 21:34 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +		var addon_dir = str(ADDONS_PATH) + file #ADDONS_PATH.plus_file(file)
If you switch this back to a String, then this change isn't necessary.

2021-08-21 21:34 UTC, willnationsdev commented on project.godot
> +enabled=PackedStringArray("res://addons/godot-plugin-refresher/plugin.cfg")
Somehow this changed to an absolute path. I'm not sure if there's anything you can/should do about it though since this seems like a value that the Godot Editor code handles updating.

2021-08-21 21:34 UTC, willnationsdev commented on project.godot
> +"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"store_command":true,"alt_pressed":false,"shift_pressed":false,"meta_pressed":false,"comman
Can you visually cross-reference these in the ProjectSettings' InputMap to make sure that nothing looks different/off? I'm guessing it's fine, but wanna be sure.

2021-08-21 21:40 UTC, nonunknown commented on addons/godot-plugin-refresher/plugin_refresher.tscn
>  dialog_autowrap = true
Yeah it was done automatically!

2021-08-21 21:43 UTC, nonunknown commented on project.godot
> +enabled=PackedStringArray("res://addons/godot-plugin-refresher/plugin.cfg")
this was done autamatically too!

2021-08-21 21:47 UTC, nonunknown commented on project.godot
> +"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"store_command":true,"alt_pressed":false,"shift_pressed":false,"meta_pressed":false,"comman
Have no idea on how to confirm this

2024-12-07 20:18 UTC, willnationsdev commented
Hey there. I'm finally back after a 3-year hiatus from Godot. Sorry that I never got these issues/PRs sorted out. For now, I'm closing this since #31 was already updated for the latest Godot 4 release, but I appreciate the time you spent on this back then. I hope the tool has nonetheless proved useful to you, even if it was just your own maintained copy. 😅

2024-12-07 20:18 UTC, closed without merging