update to v2.0
godot-extended-libraries/godot-plugin-refresher pull request #20
Opened 2022-01-11 14:14 UTC by WhalesState

> **why v2.0** ?
>
>> 1- Because I have made lots of changes in the scripts which makes it a remake of the plugin.
>>
>> 2- I have added a checkbox to allow you to toggle a plugin on/of and to notice if it's enabled or not when you choose it.
>>
>> 3- Fixed a bug that it always choose the first menu item on filesystem changes.
>>
>> 4- Updated the README.md.
>>
>> 5- Updated the godot.project to the last stable version 3.4.2.
>>
>> 6- Added comments to every function that helps you understand what it easily.

**feel free to credit me if you like, i commented the Ko-fi , please uncomment back on release. thank you!**

2022-01-13 16:06 UTC, WhalesState commented
@willnationsdev @aaronfranke @Xrayez @Calinou
hello , this is my first pull request on github, anyone available to review it ?

2022-01-15 18:47 UTC, aaronfranke requested changes
Lots and lots of problems with this PR.

PRs should be for specific changes. It's not helpful to make a PR called "update to v2.0". The repo owner should decide on versioning, while PRs should have specific changes. It's very difficult to review PRs that change every line of code.

Do not ping people on GitHub that have nothing to do with this repo. Do not ping Calinou for example.

Lots of commits that should be squashed. "fix" is not a useful thing to have in the history.

> Updated the README.md.

You made it worse by removing the Ko-Fi link and nesting things in unnecessary quotes.

I wrote some specific comments below for the code. I could go on, but as I mentioned it's incredibly difficult to review PRs that change every single line of code, even if you fixed all of these problems there would probably be dozens more and it seems unlikely this will be merged. I am writing this as a courtesy to you so that you know how to contribute to projects in the future.

2022-01-15 18:47 UTC, aaronfranke commented on README.md
> +<dev align = center>
I'm pretty sure that `<dev>` is not a valid tag. Did you mean `<div>`?

You really shouldn't be using HTML in the first place though. Prefer vanilla markdown.

2022-01-15 18:47 UTC, aaronfranke commented on addons/godot-plugin-refresher/plugin.cfg
> +description="A toolbar addition to facilitate toggling on/off a selected plugin."
The existing order is how it works though. It turns a plugin off, then it turns it on again.

2022-01-15 18:47 UTC, aaronfranke commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +func _ready()-> void:
```suggestion
func _ready() -> void:
```

2022-01-15 18:47 UTC, aaronfranke commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +	assert(OK == $ConfirmationDialog.connect('confirmed', self, '_on_ConfirmationDialog_confirmed'))
Not following the GDScript style guide, `"` should be preferred to `'`.

2022-01-15 18:47 UTC, aaronfranke commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +#* update `options` button items
It's not clear what `#*` is supposed to mean. The comments aren't properly capitalized either.

2022-01-16 09:32 UTC, WhalesState commented on README.md
> +<dev align = center>
thank you so much for explaining the issues, i just saw the fork appears on my profile and i didn't know what to do with README.md.

2022-01-16 09:37 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +#* update `options` button items
#* makes the comment line color green in vscode , and the * makes the comment appears nested when i add more lines under it using #* *, it's like making your own hints when you hover over your custom functions that has comments above , and it can be styled.

2022-01-16 11:24 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher.gd
> +func _ready()-> void:
thank you so much for the info, check now if it's better and tell me if there's any mistake, I'd like to learn from you.

2022-01-19 13:43 UTC, WhalesState commented
> Lots and lots of problems with this PR.
> 
> PRs should be for specific changes. It's not helpful to make a PR called "update to v2.0". The repo owner should decide on versioning, while PRs should have specific changes. It's very difficult to review PRs that change every line of code.
> 
> Do not ping people on GitHub that have nothing to do with this repo. Do not ping Calinou for example.
> 
> Lots of commits that should be squashed. "fix" is not a useful thing to have in the history.
> 
> > Updated the README.md.
> 
> You made it worse by removing the Ko-Fi link and nesting things in unnecessary Markdown quotes.
> 
> I wrote some specific comments below for the code. I could go on, but as I mentioned it's incredibly difficult to review PRs that change every single line of code, even if you fixed all of these problems there would probably be dozens more and it seems unlikely this will be merged. I am writing this as a courtesy to you so that you know how to contribute to projects in the future.

2022-01-20 22:47 UTC, WhalesState commented
@aaronfranke can you check it now after the changes ?

2022-01-21 06:04 UTC, willnationsdev commented
@WhalesState Hey, l'm gonna have a look over what you've submitted tomorrow. I was going to earlier, but I've been busy with some urgent things at work. Very interesting stuff so far with what I've browsed. Thanks!

2022-01-21 09:11 UTC, WhalesState commented
@willnationsdev 
you're welcome, and take your time, the reason why I remade it is because at first when I looked at the code there was so many things that I don't understand, so I started to search and learn about every method you used from docs and printing the values, I have learnt a lot from it <3 thank you too ^^

2022-01-22 05:12 UTC, willnationsdev requested changes
Lots of interesting adjustments and cleanup here, which I greatly appreciate, but overall you've made a great many arbitrary alterations that deviate from the community standards, so please make the necessary adjustments to fix those and it'll be looking much better.

Thank you so much for your patience.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +var refresher_scene = load("res://addons/godot-plugin-refresher/plugin_refresher.tscn") as PackedScene
Did you intend to statically type these variables? If so, you'll need `:=` for type inference.

Also, does not appear to ever be modified (at least, in this script). If it is intended to be immutable, I would recommend declaring it as a `const` and using `preload(...)` instead.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +var refresher : HBoxContainer
Please follow the official GDScript style guide for [colon placement of static variable declarations](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#declared-types). And while we're at it, it's probably better to adopt for explicitness in the null assignment (though I notice I didn't have it that way originally).

```gdscript
var refresher: HBoxContainer = null
```

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +	var _theme = get_editor_interface().get_base_control()
Given that everything is else is statically typed, I recommend doing it here too for consistency.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +		if _dir.dir_exists(_addon_dir) and !_is_cur_plugin:
It's become more noticeable here, but I see you've done it most everywhere else too; try to update all of your changes across these files to match the [official GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html) when making contributions. It's one thing if it were code for one's private use, but when sharing code in the community, it's best to adhere to publicly maintained standards for improved shareability/readability. This means...

1. Using underscore prefixes for local variables will be confusing/misleading to readers who might otherwise have expected it to reference a "private" class member variable.
2. Using the `not` keyword in place of the `!` operator for boolean expressions (especially sticks out here since you're juxtaposing `and` and `!`).
3. Maintaining underscore prefixes on would-be private methods that you removed in various places of these files.
4. (Edit) Also, signal callback names like `_on_Checkbox_toggled` should retain `snake_case` formatting w/o the inclusion of `PascalCase` names (e.g. `_on_checkbox_toggled`) unless you are dealing with auto-generated callback names and your project specifically wants to keep them that way (which these scripts were not doing).

It's also relevant because you are making edits to code that was authored by someone else. Adhering to the style of the existing code is a means of respecting the original work. I *am* really liking the behavioral changes you've made though, especially the asserts at the start.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +			var _p_name: String = _plugin_cfg.get_value("plugin", "name", _file)
Could we rename `_p_name`? I see it was listed as `display_name` before, but as it is... `p_*` is a pattern that is often used in the Godot source code to indicate the symbol refers to a parameter rather than a local or member variable, so it can be misleading here. (Edit: I see you do this yourself later on, so you know). You can probably just call it `name` here and that'd be fine.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +		plugin_config.load(_cfg_path)
Shouldn't this also have an `assert(OK == ...)` wrapper, like the ones above?

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +func load_settings()-> void:
This is part of the style guide related comments, but your renaming of methods to remove leading underscores is another thing I'd prefer to revert. If the method is intended to only be called by the class that owns the method, then it [should have a leading underscore to mark it as such](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#functions-and-variables). Only methods that are presumed to be exposed for public consumption should lack leading underscores.

2022-01-22 05:12 UTC, willnationsdev commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +func is_enabled(_p_name: String) -> bool:
Mentioned previously, but re-iterating as another example: all of these `_p_name` variables should be `p_name` since they are not private class member variables.

2022-01-22 05:25 UTC, willnationsdev requested changes

2022-01-22 05:25 UTC, willnationsdev commented on README.md
> +> > 3- a **`Refresh`** Button to toggle it off then on.
Also, as aaron mentioned, please don't double-nest quoted segments like this. Just restore the original numbered list format as it is easier for people to read. You can use different levels of headers to make the hierarchical subdivisions in the content instead.

2022-01-22 05:25 UTC, willnationsdev commented on README.md
In the process, you've also removed the "this is what happens instead" segment. I'm not *opposed* to taking it out, but only if it can be reasonably replaced with something better. If you intend to add screenshots and embed them, that'd be good, but it not, please restore the original text.

2022-01-22 05:25 UTC, willnationsdev commented on README.md
> +> **It adds this to the main toolbar in the top-right Corner**:
Reword to `It adds [the following changes] to the main toolbar's top-right corner:`

1. `this` implies a singular item, but you then list several.
2. `Corner` is mistakenly capitalized.

2022-01-23 09:48 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +var refresher_scene = load("res://addons/godot-plugin-refresher/plugin_refresher.tscn") as PackedScene
yes, i just have learned it when `Aaron` kept asking me to follow the `gdscript style guide sheet`, so finally i have looked at it and have realized that i was just doing things in my own fancy way which is marked as bad in the sheet, i will be correcting it based on what i have learnt recently and your criticize, also sorry for the later reply, i was moving from windows to ubuntu so it was a long process to make sure i didn't miss any backup before purging windows and to prepare my new OS for work. thank you.

2022-01-24 05:10 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +		if _dir.dir_exists(_addon_dir) and !_is_cur_plugin:
i fixed the previews issues alongside changing `"!" to "not"` and the signal names to `snake_case`, and fixed many other bad styles that i noticed while reviewing the code, but i didn't change the `local variables` yet because i just saw it now, i didn't like this comment yesterday since i only have read the previews ones first and waited until i fix the script first then i go along the other comments one by one.
i do it most of the time in all my scripts to avoid shadowing another variable name, since they are local and won't be accessed, but what i have learnt from you that it's only usable in functions `params/args` and private declaration inside a class. it's like if they are local then they are private, and if anyone wanted to contribute he is free to rename his variables and they will not conflict with other local variables from any function, shadowing another variable is annoying since you will be forced to change your variable name or the local variable name and edit the whole function, will we leave it like this to avoid this issue in the future or we change the local vars ?

2022-01-24 05:15 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +			var _p_name: String = _plugin_cfg.get_value("plugin", "name", _file)
yes display_name will be better than p_name, i always try to find easy names that refers to the variable, i will change it.

2022-01-24 05:22 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +			var _p_name: String = _plugin_cfg.get_value("plugin", "name", _file)
but to avoid the confusion that already happened to me when i first looked at the while loop, we can rename them like `display_name` which is the name that we get from the `Configure file` -> "Plugin Refresher", and `plugin_name` which is the name that godot use to refer to the `Plugin` -> "plugin_refresher", it will be easier for us since we are dealing with two names at same time

2022-01-24 05:33 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +		plugin_config.load(_cfg_path)
are you wearing glasses in real? you have got me xD i missed it, sorry.

2022-01-24 05:43 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +func load_settings()-> void:
nice, i didn't know that, i think i didn't see such thing while reading the style guide, i also realized that the hidden nodes in the editor scene tree uses such thing in some hidden classes. like the CanvasItemEditor node, they hide the functions and the classes from us !! xD but i reach them and i edit, gladly we have `get_method_list()` to find such things

2022-01-24 05:48 UTC, WhalesState commented on addons/godot-plugin-refresher/plugin_refresher_plugin.gd
> +func is_enabled(_p_name: String) -> bool:
ok, i finished reading all, it's clear. thank you so much for the useful information that you shared, i have learnt a lot from you, i will make some coffee rn and start on preparing the second commit.

2022-01-24 05:50 UTC, WhalesState commented on README.md
> +> > 3- a **`Refresh`** Button to toggle it off then on.
i recently have learnt very few things about the markdown style, i think i need to read the github markdown guide and start fixing it yes, let me do it after i fix the scripts.

2022-01-24 05:53 UTC, WhalesState commented on README.md
yes we need to include some photos in the .md, this plugin already don't need an introduction, it's a trademark xD, i just tried to make it short and clean as much as i can so people will not skip it.

2022-01-24 05:55 UTC, WhalesState commented on README.md
> +> **It adds this to the main toolbar in the top-right Corner**:
clear, i will make some coffee now and finish the scripts, thank you so much for all the useful information, i have learnt a lot.

2022-01-24 07:10 UTC, WhalesState commented on README.md
> +> **It adds this to the main toolbar in the top-right Corner**:
i have finished all the previews changes that you have requested, and changed the variable names to be more detailed and made the scripts easier to be understood by other contributors. let me test it now and change then i will prepare the md file.

2022-01-24 07:20 UTC, WhalesState commented on README.md
> +> **It adds this to the main toolbar in the top-right Corner**:
i will debug and run Godot with those flags to track what happens when the projects opens and closes in the next frame
`--no-window -d --disable-render-loop -v -q`
i already have added this line to vscode.code-runner plugin settings
`
"code-runner.executorMap": {
        "gdscript": "/home/$home/godot-engine/godot.64 /home/$home/projects/godot-plugin-refresher/project.godot --no-window -d --disable-render-loop --frame-delay 0 --print-fps -v -q"
        }
`
so it makes me able to use the gui run button to run godot from terminal with any desired flags, i leave some flags like --frame-delay just in case i removed the -q <Quit> flag from the end

2022-01-24 07:35 UTC, WhalesState commented on README.md
> +> **It adds this to the main toolbar in the top-right Corner**:
this is the result, everything seems fine now
`
EditorSettings: Save OK!
Loading resource: res://addons/godot-plugin-refresher/plugin_refresher_plugin.gd
Loading resource: res://addons/godot-plugin-refresher/plugin_refresher.tscn
Loading resource: res://addons/godot-plugin-refresher/plugin_refresher.gd
Loading resource: res://addons/godot-plugin-refresher/plugin_refresher.tscn
Editor FPS: 1 (1000.0 mspf)
EditorSettings: Save OK!
`
i will have a look now on github md tutorial and try to make the md file looks better with an image and i will make an icon for the plugin

2022-01-24 09:04 UTC, WhalesState commented
@willnationsdev
created this icon for the asset-library, please check the files and tell me if i missed anything, thank you
![icon](https://user-images.githubusercontent.com/53877170/150752679-bb919f4b-c09f-4580-8b75-b7825108bf2d.png)

2022-01-24 09:17 UTC, WhalesState commented
#### it will be nice if you updated the about section on the repo to include the changes, thank you!

2023-08-16 02:14 UTC, closed without merging